### ISSUE TITLE
bug(eslint-config-neon/angular) <> Template Error: templateRules is not a function

### ISSUE THREAD

**Issue by JPBM135** [iCrawl/eslint-config-neon#6]
### Error stack trace:

```
Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: Cannot read config file: /**/node_modules/eslint-config-neon/angular.js
Error: templateRules is not a function
Referenced from: /**/packages/client/.eslintrc.json
    at Object.<anonymous> (/**/node_modules/eslint-config-neon/src/angular.js:125:11)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/**/node_modules/eslint-config-neon/angular.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
```

### Vesions:

**Node:** `v18.19.0`

```json
{
    "eslint": "8.56.0",
    "eslint-config-neon": "0.1.59",
    "typescript": "5.0.3"
}
```

### Config used:

Root:
```
{
	"root": true,
	"parserOptions": {
		"project": "./tsconfig.eslint.json"
	}
}
```

Client:
```json
{
  "extends": ["../../.eslintrc.json"],
  "env": {
    "es6": true
  },
  "parserOptions": {
    "ecmaVersion": 2018
  },
  "ignorePatterns": ["src/@fuse/**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "neon/common",
        "neon/browser",
        "neon/node",
        "neon/typescript",
        "neon/angular",
        "neon/rxjs",
        "neon/rxjs-angular",
        "neon/prettier"
      ],
      "rules": {
        "n/no-sync": "off",
        "@angular-eslint/use-component-view-encapsulation": "warn",
        "@typescript-eslint/prefer-nullish-coalescing": "error",
        "no-restricted-imports": [
          "error",
          {
            "name": "@apollo/client",
            "message": "Importar o @apollo/client vai gerar erros, use o @apollo/client/core"
          }
        ],
        "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
        "rxjs/no-implicit-any-catch": "off",
        "@typescript-eslint/no-unused-vars": "error",
        "no-restricted-globals": "off",
        "unicorn/prefer-node-protocol": "off"
      }
    },
    {
      "files": ["*.html"],
      "parser": "@angular-eslint/template-parser",
      "plugins": ["@angular-eslint/template"],
      "rules": {
        "@angular-eslint/template/alt-text": 2,
        "@angular-eslint/template/elements-content": 2,
        "@angular-eslint/template/label-has-associated-control": 1,
        "@angular-eslint/template/table-scope": 2,
        "@angular-eslint/template/valid-aria": 2,
        "@angular-eslint/template/banana-in-box": 2,
        "@angular-eslint/template/button-has-type": 2,
        "@angular-eslint/template/click-events-have-key-events": 2,
        "@angular-eslint/template/conditional-complexity": 0,
        "@angular-eslint/template/cyclomatic-complexity": 0,
        "@angular-eslint/template/eqeqeq": 2,
        "@angular-eslint/template/i18n": 0,
        "@angular-eslint/template/mouse-events-have-key-events": 2,
        "@angular-eslint/template/no-any": 0,
        "@angular-eslint/template/no-autofocus": 2,
        "@angular-eslint/template/no-call-expression": 0,
        "@angular-eslint/template/no-distracting-elements": 2,
        "@angular-eslint/template/no-duplicate-attributes": 2,
        "@angular-eslint/template/no-negated-async": 2,
        "@angular-eslint/template/no-positive-tabindex": 2,
        "@angular-eslint/template/use-track-by-function": 1
      }
    }
  ]
}

```

**Comment by JPBM135** [comment]
Working on a fix and will PR today!
